import Foundation
var city: String = "Istanbul"
var country: String = "Turkey"
var phone: String = "555-555-5555"
var postalCode: String = "34000"
var email: String = "example@email.com"
var profession: String = "Developer"
var stockAmount: Int = 20
var customerName: String = "John Doe"
var balance: Double = 1000.0
var birthday: Date = Date()
var salary: Double = 5000.0
var maritalStatus: String = "Single"
var productComment: String = "Great product!"
var paymentDate: Date = Date()
var paymentMethod: String = "Credit Card"
var orderQuantity: Int = 2
var carModel: String = "Audi A4"
var bookTitle: String = "The Lord of the Rings"
var publicationDate: Date = Date()
var discountAmount: Double = 100.0
var roomCount: Int = 3
var latitude: Double = 41.01384
var longitude: Double = 28.94966
var productName: String = "iPhone 12"
var mealPrice: Double = 15.0
var brand: String = "Apple"
var musicTitle: String = "Shape of You"
var videoDuration: Double = 4.0
var productRating: Double = 4.5
var imageName: String = "productImage.jpeg"
var fileFormat: String = "JPEG"
var color: String = "Black"
var colorCode: String = "#000000"
var phoneModel: String = "iPhone 12 Pro"
var screenSize: Double = 6.1
var weight: Double = 300.0
var nationalDay: String = "October 29"
var holiday: String = "New Year's Day"
var reservationDate: Date = Date()
var streetName: String = "Main Street"
var busLine: String = "34B"
var remainingMinutes: Int = 30
var trackingCode: String = "XZY123"
var couponDuration: Int = 7
var couponCode: String = "SAVE50"
var billingAddress: String = "123 Main St, Anytown USA 12345"
